### ISSUE TITLE
Remove huge deleted files (demo.gif) from Git's history

### ISSUE THREAD

**Issue by vibl** [danny-avila/chatgpt-clone#161] opened 2023-04-06 12:05 UTC
The size of the repository is huge: 140 MB. Most of it is due to a few `demo.gif` files that have been deleted but still are in Git's history:

Commands to find them:
```
git verify-pack -v .git/objects/pack/pack-*.idx | sort -k 3 -n | tail -10

git rev-list --all --objects | grep <object-sha1>

```
Commands to remove them safely:
```
git filter-repo --invert-paths --path images/demo.gif --path demo.gif --path client/public/demo.gif --path public/demo.gif
```
(From https://github.com/newren/git-filter-repo/)

Down to 7.6 MB!

**Comment by danny-avila** [comment] 2023-04-06 14:26
Thanks for bringing this to my attention.

I can confirm it reduces the size locally, and it did seem to rewrite history when i tried a force push. however, when i try to clone the repo again, it's still at 140 mb, any idea why? the push did remove a commit as far as i could tell

**Comment by danny-avila** [comment] 2023-04-06 14:28
Ran this twice, on second time, with local file size removed again and history rewrite, the push said all up to date.

**Comment by danny-avila** [comment] 2023-04-06 14:34
is it because the other branches have it in their git history maybe? hmm

**Comment by danny-avila** [comment] 2023-04-06 16:51
No worries, I'll try again once the other branches are merged

**Comment by danny-avila** [comment] 2023-04-08 13:36
After trying this again with no other branches in the repo, I believe this is something on github's end needing to garbage collect on the repo, which is done every few weeks. I'll check back in a month.. When I clone down the repo, I can view the commit with `git rev-list --all --objects | grep demo.gif` but it is not existent on github

**Closed by danny-avila** 2023-04-08 13:36 UTC

**Comment by danny-avila** [comment] 2023-04-21 14:45
@vibl I just wanted to let you know I finally got this fixed. I talked to github support to reset the cache, and after they did so, I realized the problem was the image still existing in the tags. The repo will clone down at around 8 MB now!

**Comment by vibl** [comment] 2023-04-21 14:49
Great :-) Thank you for your work!
