### ISSUE TITLE
bug: I cannot delete the latest word in input editor, while gpt is talking.

### ISSUE THREAD

**Issue by wtlyu** [danny-avila/chatgpt-clone#66] opened 2023-03-13 18:44 UTC
reproduce:

1. ask a question
2. while gpt is talking, write something in input panel, then delete
3. we can see the latest character cannot be deleted.
4. once finished, it can be deleted.

Not sure if this bug exist in master branch

**Comment by danny-avila** [comment] 2023-03-13 18:49
in master im able to 'delete' by using backspace, but not with 'delete' key nor if i select all and backspace. could be something with the input state

**Comment by wtlyu** [comment] 2023-03-13 19:03
> in master im able to 'delete' by using backspace, but not with 'delete' key nor if i select all and backspace. could be something with the input state

check again, I can't delete, by anyways.

this line block me 

<img width="492" alt="image" src="https://user-images.githubusercontent.com/8267138/224802834-09df996a-b002-4327-8d9c-26d348646e08.png">


when isSubmitting is true, this if block is activated. 
at that time, the original value of input is 'a', then I press backspace, so e.target is '', value = ''. Then the value will not be saved into state. remaining 'a'

**Comment by danny-avila** [comment] 2023-03-17 16:59
@wtlyu not sure what you mean, but i removed the placeholder and disabling of the textarea in favor of allowing text input, while disallowing submission while a message is being rendered. this was my original design and seems to work as intended, not sure what else you were doing with the submit state that you needed to disable the textarea. this particular issue is fixed now in #87

**Closed by danny-avila** 2023-03-17 16:59 UTC

**Comment by wtlyu** [comment] 2023-03-17 18:19
I agree with your origional design. When gpt is responsing, we can allow user to write something (but cannot sent it out)

In my PR #88, this feature is also keeped. 

Plus new feature: if there is something that block sending new message (which is : message is error or cancelled), the input area will show the warning message and user input will be hidden, but once recovered (for example, regenerating the cancelled message), the text will come back again.

but the bug is that, while a long response is receiving (isSubmitting = true), if I type something in the input area, then I can delete almost characters, except the last one. That 'if' line reject the last deletion.
